### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by FlorianLudwig** [podenv/silverkube#4]
the master branch contains useful fixes for running in a desktop environment. A new release would be great :)

**Comment by TristanCacqueray** [comment]
Good point, I'm building a new package and will do a `0.2.0` release. Glad you find it useful :-)

**Comment by TristanCacqueray** [comment]
The HEAD is now tagged and released at https://github.com/podenv/silverkube/releases/tag/0.2.0 .

If you experience any difficulties, please don't hesistate to raise an issue.
