### ISSUE TITLE
update this to F36 / CoreOS

### ISSUE THREAD

**Issue by outbackdingo** [podenv/silverkube#6]
you have a feasible and decent idea here, a bit similiar to QubesOS Desktop which does XEN/VMs and a UI, you should really do this on a new instance of silverblue or kinoite  F36 spins ..... you just might have the next remote desktop idea.

**Comment by TristanCacqueray** [comment]
Thank you for the feedback. Though, desktop environment requires a lot of work, and I've not been able to realize silverkube goals (yet). In particular, I've added a note to the README about the security requirement where I think systemd-login is necessary to setup the permission, and I don't think a rootless process can do that securely.

Anyway, I've created a new release with a f36 package. Cheers!
